### ISSUE TITLE
Kanban Board Planning

### ISSUE THREAD

**Issue by wassimchakib** [wassimchakib/Car-Rental-Front-End#16]
- In this project, we planned the kanban board for the next 2 weeks, please find the link to the kanban [here](https://github.com/users/wassimchakib/projects/13)

- We are a team of 4 people : @Profsain @wassimchakib @Kweeka1 @KIsmoilov  
![image](https://user-images.githubusercontent.com/50754458/229162056-02f608c7-85bb-4730-83b0-a05739f9ee11.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- Good job meeting all the requirements 👍 

## Optional suggestions
- Consider adding labels to help with filtering with types of tasks and distinguishing types of tasks

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
